export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";
export const GET_EMPLOYEES = "SEARCH_EMPLOYEES";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SORT_EMPLOYEESDOB = "SORT_EMPLOYEESDOB";
export const SORT_EMPLOYEESNAME = "SORT_EMPLOYEESNAME";
export const SET_SORTEDNAME = "SET_SORTEDNAME";
export const SET_SORTEDDOB = "SET_SORTEDDOB";
